### ISSUE TITLE
Bulk API error

### ISSUE THREAD

**Issue by rommmy** [intercom/intercom-php#112]
Hi,

The bulk endpoint gives an error when trying to bulk update users. The response object gives me the following error https://api.intercom.io/jobs/job_fc818dca_718f_11e5_b9f6_61cc213f55b0/error

Basically it is complaining about a wrong Accept header, but I'm sending the correct value "application/json".

**Comment by josler** [comment]
Hi @rommmy - when following that error link you need to provide the Accept header (and auth etc.) for that request too. It's just providing the URL. We don't currently have a way to auto follow these links properly from within the PHP library itself.
