### ISSUE TITLE
How can assigne a chat to and admin ?

### ISSUE THREAD

**Issue by ArielBadilla** [intercom/intercom-php#120]
Hi

I need to asign using  a conversation to an Admin using intercom API. I found in this link https://github.com/intercom/intercom-ruby/issues/181 that Intercom was working on in but I still don't see any documnetation about how to do it. Do you know if is posible ?

Thanks

**Comment by bobjflong** [comment]
Hi @ArielBadilla you can use the `assignment` message type as in the docs. Here's an example in the tests: https://github.com/intercom/intercom-php/blob/master/tests/Intercom/Resources/ConversationTest.php#L125
