### ISSUE TITLE
Not Working Need to fix default Accept Header for CURL PHP

### ISSUE THREAD

**Issue by kbhagchandani** [intercom/intercom-php#130]
Today i have tried to integrate Intercom IO with one of my projects and i had to waste lots of time finding this issue. Intercom site is not providing any response without HTTP ACCEPT header being set to "application/json". Please set it as the default header in all curl requests to make a use of this library.

If possible then please provide option for debuging by setting CURLOPT_VERBOSE to true. You can also raise an exception if the response from server is other then HTTP 200, like in this case it is always 406.

## Version info
  - intercom-php version: 1.5
  - PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

## Expected behavior
An array list of companies

## Actual behavior
Null

## Steps to reproduce
 1. Install provided setup with composer.
 2. Set up a call to get companies list 
 3. check the result

**Comment by travega** [comment]
Hey @kbhagchandani, the accept header is defaulted in the `IntercomAbstractClient`. You can use the `getDefaultConfig()` function to get the defaulted headers. Hope this helps :+1:
