### ISSUE TITLE
ClientErrorResponse exception too general, all code/type info is in message string

### ISSUE THREAD

**Issue by mikegioia** [intercom/intercom-php#131]
## Version info
  - intercom-php version: v1.5.0
  - PHP version: 5.5.9-1ubuntu4.14

## Expected behavior
1. When running a batch update (i.e. tagCompanies()) I expect the update to go through and return any error info in the event of an error. For example, if I batch update 50 company IDs to have tag "xyz", and if one of those company IDs doesn't exist for our account, I would except to receive 20x response that 49 were updated and 1 didn't exist.

2. When receiving a ClientErrorResponseException error I would except the code to not be 0, and for the code/reason info to not be garbled into a string that I have to manually parse. I would also expect different errors to be handled with different exceptions, and not one catch-all exception used with the entire contents forced into the exception message string.

## Actual behavior
There are a couple problems here:

1. Why am I getting a "404" error when a company ID doesn't exist in a batch update? That doesn't make any sense and actually took me an hour of debugging thinking the endpoint URL was wrong before I realized what was going on!!!

2. If you DO return a 404, why is that not a CompanyNotFoundException? I can catch specific errors and handle them accordingly but instead you use one generic ClientErrorResponseException and put the code as a string (!) into the exception message. This makes exception handling nearly impossible and it forces me to custom-parse your error string.

## Steps to reproduce
```
$intercom = IntercomBasicAuthClient::factory([
    'app_id' => '123456abcdef',
    'api_key' => '123456'
]);
$intercom->tagCompanies([
    "name" => 'xyz',
    "companies" => [
        [ "company_id" => "goodId123" ],
        [ "company_id" => "badId123" ]
    ]
]);
```

This fails to update "goodId123", throws a ClientErrorResponseException with the payload:
```
Client error response
[status code] 404
[reason phrase] Not Found
```

## Logs
Not needed

**Comment by bobjflong** [comment]
Hi @mikegioia 

The API is designed fairly RESTfully, split into resources:

> Why am I getting a "404" error when a company ID doesn't exist in a batch update?

The answer to this is because the resource is Company and the resource cannot be found with your supplied parameters.

A missing endpoint is pretty rare (ie. I don't think it's ever happened). You don't need a different exception class for each endpoint, and you don't need to parse the error message. The 404 will tell you if the resource is missing (and other 4xxs will correspond to other types of client errors). In other words, we try to use HTTP instead of rolling our own error signalling.

I hope that helps explain our methodology.

**Comment by mikegioia** [comment]
No @bobjflong it doesn't explain it. If I send a batch update of 50 company IDs and 1 company doesn't exist, the whole response returns a 404. I don't understand how that makes sense. If it was a single company I could understand that, but this is a batch update.

You're even returning WHICH company didn't exist. It's just a full stop 404. Do you see how this causes problems during batch updates? I can't know which one failed, and the 49 others didn't go through. So now I have to do them 1 at a time which will defeat the purpose of the batching and cause me to run over my rate limit!

**Comment by bobjflong** [comment]
We are designing appropriate APIs for bulk updates: https://developers.intercom.io/reference#bulk-apis

(Which don't have company tagging right now).

Why not get in touch through the Intercom messenger (ask for Bob) and we can substantially increase your rate limit if you explain what you need.
