### ISSUE TITLE
syntax error, unexpected 'function' on /IntercomClient.php on line 7

### ISSUE THREAD

**Issue by defaria** [intercom/intercom-php#136]
I am new to intercom. I installed it using composer, but I have also tried just including all dependencies myself.

Either way, when I run the following:

`$client = new IntercomClient('######','#########');`

I get the following error:

Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /vendor/intercom/intercom-php/src/IntercomClient.php on line 7

Line 7:

`use function GuzzleHttp\Psr7\stream_for;`

PSR7 is installed and so are all other dependencies.

Any ideas?

**Comment by tremby** [comment]
This is a dupe of #134. See also #135. You need PHP 5.6 to use this package.

**Comment by defaria** [comment]
well that sucks... thanks for letting me know though.

**Comment by tremby** [comment]
It's a *very* thin client. Just have a look over the source code; you can easily use Guzzle directly yourself and make the same calls.

**Comment by defaria** [comment]
I decided to just use curl directly.

**Comment by nezaboravi** [comment]
as i commented on other ticket, i am having php 5.6.30 and getting same error
