### ISSUE TITLE
Items not updating

### ISSUE THREAD

**Issue by george-oakling** [intercom/intercom-php#150]
## Version info
  - intercom-php version: v2.0.0
  - PHP version: 5.6.20

## Expected behavior

Updating user identified by email should update items like name, etc.. I tried this:

```
$user = [
	'email' => 'my@mail.com',
	'name' => 'Changed name',
];
$response = $client->users->create($user);
```

Dumping $response shows correct information about user with newly set up name parameter. But when I open Intercom and find by email, user has the old name.

## Steps to reproduce
 1. create user
 2. try to update params like name
 3. the old param values are in Intercom

**Comment by bobjflong** [comment]
Hi @george-oakling 

Can you explain a little bit more? There may be some lag (should be less than 5 minutes) before updated information appears in the user list. Can you clarify your app_id, the email you are using, and the name change in Intercom? Also screenshots would help a lot.

**Comment by george-oakling** [comment]
Hi, I think that mentioning that there is a 5 minutes lag is enough :) I tested it, waited for that period and it seems it gets updated after that time, will track this for next week, in any case of problems, I will write aditional info to this issue.

**Comment by george-oakling** [comment]
Thank you :)

**Comment by bobjflong** [comment]
👍 thanks
