### ISSUE TITLE
Intercom version 2.0.0 is importing namespaced function (php 5.6 functionality) 

### ISSUE THREAD

**Issue by slavo2** [intercom/intercom-php#153]
## Version info
  - intercom-php version: 2.0.0
  - PHP version: 5.5

## Expected behavior

Creating object client 

## Actual behavior

crashing with error complaining about unexpected 'function' in IntercomClient.php line 7

## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1.  create IntercomClient object 
 2.  run code using php version 5.5
 
## Note:
it would be nice, if new release 2.0.1 would be made, which does not expect php 5.6+ functionality

**Comment by bobjflong** [comment]
Hi @slavo2 we've [decided not to support older versions of php](https://github.com/intercom/intercom-php/pull/147#issuecomment-233319564).

There are some 3rd party packages that promise backwards compatibility, that you may want to evaluate: https://packagist.org/packages/gayanhewa/intercom-php
