### ISSUE TITLE
Second instance is not creating after calling intercom instance

### ISSUE THREAD

**Issue by martinjp1** [intercom/intercom-php#156]
Hi

I installed intercom PHP from https://github.com/intercom/intercom-php .
When I created second instance after created first intercom instance, second instance is not working.
Second instance is for other class.
For example:

require "./vendor/autoload.php";
1) $client = new IntercomClient();
$client->users->create([
  "email" => "test@intercom.io"
]);

2) $usersMdl = new App_Models_Users();

Second instance is not working.  When IntercomClient(); instance is not there. Second instance ie working fine
## Version info
- intercom-php version: latest
- PHP version: 7.0.8
## Expected behavior

The instance which is created after intercom client will work as like other instances
## Actual behavior

The instance which is created after intercom client is not working
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
1. create intercom instance
2. create another instance after intercom instance
3. 
## Logs

instance is not found

**Comment by lucasbicalleto** [comment]
Hello friend, is to give me a hand?

I have error in `Vendor/autoload.php` a look at my problem , please?

https://github.com/intercom/intercom-php/issues/160

**Comment by Skaelv** [comment]
Is this still happening?  
Please reopen if it does.  
I'm going to close for now as it seems outdated.
