### ISSUE TITLE
Install with PHP version 5.5 it's not possible

### ISSUE THREAD

**Issue by sinner** [intercom/intercom-php#157]
I love to stay updated, but IT department upgrade the PHP versions only with the OS Repositories. In our current platform we have 5.5.9 version of PHP.

I think that your business is justly to have more clients using your platform. I think too this situation is present in a lot of organizations, so I think that you have to keep in mind this limitation to fix them. It's only a suggestion, or maybe you can release a version to PHP 5.5 -at least- and other to the current PHP Version like PHP 7 -i.e.-

## Version info
  - intercom-php version: v3.0.0
  - PHP version: PHP 5.5.9

## Expected behavior
  - To be installed

## Actual behavior
  - It's not installed when you have PHP 5.5 version

## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1. You need to have PHP 5.5.X.
 2. execute: composer require intercom/intercom-php

## Logs
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - intercom/intercom-php v3.0.0 requires php >= 5.5.9 -> your PHP version (5.5.9) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
    - intercom/intercom-php v3.0.0 requires php >= 5.5.9 -> your PHP version (5.5.9) overridden by "config.platform.php" version (5.5.9) does not satisfy that requirement.
    - Installation request for intercom/intercom-php ^3.0 -> satisfiable by intercom/intercom-php[v3.0.0].

**Comment by bobjflong** [comment]
Hi there, there is more context here: https://github.com/intercom/intercom-php/issues/146 including links to third party SDKs that have 5.5 support.
