### ISSUE TITLE
Error Intercom API

### ISSUE THREAD

**Issue by lucasbicalleto** [intercom/intercom-php#160]
Hello friends recently bought a plan intercom .

And I would like to get the following data from a form and send that data as a new User 's intercom .

However this error returning me to do this, I'm following the step by step here GitHub and even the developers documents.

`Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /home/u213882019/public_html/Intercom/user.php on line 3`

`Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/php-5.6/pear') in /home/u213882019/public_html/Intercom/user.php on line 3`

returns me that error above. I entered the SSH and gave the following command.
`composer require intercom/intercom-php` 
and I fell this screen
![image](https://cloud.githubusercontent.com/assets/20071502/17589691/8b663b66-5fac-11e6-852e-1b9cb906888b.png)

however still returns me this error `
Fatal error: Class 'GuzzleHttp\Client' not found in /home/u213882019/public_html/Intercom/Intercom/IntercomClient.php on line 71`

Please can someone help me? Thanks!

**Comment by Skaelv** [comment]
Hey @lucasbicalleto did you fix that bug? 
I wasn't able to reproduce.

**Comment by choran** [comment]
Hey @lucasbicalleto 
I am just reviewing some older issues where there has not been an update for some time.
I hope that you were able to resolve this issue in the meantime, can you let me know if you havent?
For now I will close this issue. But feel free to reopen this if you are still having issues
thanks
cathal
