### ISSUE TITLE
Function handleResponse returns an Object... Should it return an Array?

### ISSUE THREAD

**Issue by spackows** [intercom/intercom-php#168]
## Function nextPage expecting: an Array

In the docs on the intercom-php page (https://github.com/intercom/intercom-php) there is this example of how to get the next page:

```
You can grab the next page of results using the client:
$client->nextPage($response["pages"]);
```

That shows $response being an Array.  And the nextPage function in IntercomClient.php expects $pages to be an Array:

```
public function nextPage($pages)
{
    $response = $this->http_client->request('GET', $pages['next'], [
```
## Function handleResponse returns:  an Object

But the handleResponse function in IntercomClient.php returns an _object_ not n _array_:

```
private function handleResponse(Response $response){
    $stream = stream_for($response->getBody());
    //$data = json_decode($stream->getContents());           // <-- Object
    $data = json_decode( $stream->getContents(), TRUE );  // <-- Array
   return $data;
}
```
## Problem this causes

Here's some sample code showing the problem:

```
$client = new IntercomClient( '<appID>', '<apiKey>');
$conversations = new IntercomConversations( $client );
$result = $conversations->getConversations( array() );

while( $result->{"pages"}{"next"} )
{ 
    $result = $client->nextPage( $result->{"pages"} );  // <-- Fails... awkward!
}
```

Have I just missed the point somewhere??
## My hack

*I'm not saying this is the RIGHT way to make this better, or that you should do this.  I'm just including it to illustrate the problem a bit more.

Locally, I updated handleResponse in IntercomClient.php to return an array (as shown above), and that made my while loop like this, which works now:

```
while( $result["pages"]["next"] )
{ 
    $result = $client->nextPage( $result["pages"] );
}
```

**Comment by oprog** [comment]
Same issue here. Moreover I've just opened this:
https://github.com/intercom/intercom-php/issues/182

**Comment by andrewandante** [comment]
I have also experienced this problem when iterating over users. Ended up doing a horrible hack:

```
$iterator = $client->nextPage(json_decode(json_encode($iterator->pages), true)));
```

The problem lies in handleResponse as shown above. Would adding `TRUE` to the function be too breaking?
