### ISSUE TITLE
Function getConversation doesn't take options... Should it?

### ISSUE THREAD

**Issue by spackows** [intercom/intercom-php#169]
## Docs: getConversation can take an option

In the Intercom docs (https://developers.intercom.io/reference#get-a-single-conversation) it says you can optionally request that messages be returned in plain text:

![getconversation_ref](https://cloud.githubusercontent.com/assets/18294329/18683184/23b1235e-7f3d-11e6-8222-0b758673ecaa.jpg)
## Code: getConversation doesn't have a parameter for options

But in IntercomConversations.php, the function getConversation only takes one parameter:

```
public function getConversation($id) {
    $path = $this->conversationPath($id);
    return $this->client->get($path, []);
}
```
## Problem this causes

I can't retrieve the messages of a conversation in plain text.
## My hack

*I'm not saying this is the RIGHT way to make this better, or that you should do this. I'm just including it to illustrate the problem a bit more.

Locally, I updated the function getConversation in IntercomConversations.php to accept options:

```
public function getConversation($id, $options) {
    $path = $this->conversationPath($id);
    return $this->client->get($path, $options);
}
```

Now I can get messages in plain text:

```
$client = new IntercomClient( '<appID>', '<apiKey>');
$conversations = new IntercomConversations( $client );
$convo = $conversations->getConversation( $conversation["id"], array( "display_as" => "plaintext" ) );
```

**Comment by Skaelv** [comment]
Hey @spackows, thanks for reporting this one. Your "hack" looks good to me.
