### ISSUE TITLE
getUsers with Id

### ISSUE THREAD

**Issue by AntoineLemaire** [intercom/intercom-php#171]
## Version info
  - intercom-php version: 3.0
  - PHP version: 7.0

## Expected behavior

I try to get the complete user from a hook.

    $conversation = $intercomClient->conversations->getConversation($request->get('data')['item']['id']);
    dump($conversation);
    $user = $intercomClient->users->getUsers(['id' => $conversation->user->id]);
    dump($user);

`$user` should contain only one user

## Actual behavior

Even if my userId is good (https://app.intercom.io/a/apps/{myappid}/users/{myUserId}/all-conversations exist) `$user` contains a user.list with all my users. Not only the one I'm looking for

## Logs

![capture du 2016-09-22 13-19-37](https://cloud.githubusercontent.com/assets/2025537/18746401/6bcf3460-80c7-11e6-9bc3-793c4d4fd1c6.png)

**Comment by anaspk** [comment]
Hi @AntoineLemaire ,

Can you please try replacing 

`$user = $intercomClient->users->getUsers(['id' => $conversation->user->id]);`

with

`$user = $intercomClient->users->getUser($conversation->user->id);`

I hope it will give you your desired result i.e. the details of a single user.

This method `IntercomUsers::getUser()` is not part of any release yet, so, you will have to use latest code from the `master` branch.

**Comment by AntoineLemaire** [comment]
Thanks, I've just saw #163 

But the result of getUsers is still not logic right ?

**Comment by anaspk** [comment]
Is it documented somewhere in the official documentation that you can get details of a single user by id via getUsers() this way? If not, then I think getUsers() is not intended to be used for this purpose. This functionality was simply missing from Intercom PHP SDK before. However, someone from the official team can confirm further :-)

**Comment by AntoineLemaire** [comment]
Ok, in the PHP SDK 1.5 it was working with

    $user = $intercomClient->getUser(['id' => $id]);

So same parameters logic of actual `getUsers` but called with `getUser`

So the `getUser` added with #163 will be fine for me. Thanks.
