### ISSUE TITLE
Media Type not acceptable when sending bulk request

### ISSUE THREAD

**Issue by 3x14159265** [intercom/intercom-php#174]
## Version info
- intercom-php version: 2.0.0
- PHP version: 5.6.7
## Expected behavior

Updating via bulk request should not return error, that "The Accept header should send a media type of application/json".
## Actual behavior

updating users via bulk request  returns error: "The Accept header should send a media type of application/json".
This is the actual response: 
`{"app_id":"yf209ops","id":"job_v2_c5e0b20a_895d_11e6_9b38_5dea02a373e5","created_at":1475494652,"updated_at":1475494652,"completed_at":null,"name":"api_bulk_job","closing_at":1475495552,"state":"running","links":{"error":"https:\/\/api.intercom.io\/jobs\/job_v2_c5e0b20a_895d_11e6_9b38_5dea02a373e5\/error","self":"https:\/\/api.intercom.io\/jobs\/job_v2_c5e0b20a_895d_11e6_9b38_5dea02a373e5"}}`
Users are not updated in Intercom, when checking the link in "error" field, it gives me following message: 
`{errors:[{code:"media_type_not_acceptable",message:"The Accept header should send a media type of application/json"}],type:"error.list"}`
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
1. Create new IntercomClient with app_id + app_secret
2. Send bulk request with users and custom attributes, e.g.:

```
$attributes['plan'] = $user->plan;
$attributes['active'] = $user->active;
$attributes['email'] = $user->email;
$items[] = [
    'method' => 'post',
    'data_type' => 'user',
    'attributes' => $attributes
];
```
1. Get this error as response

Are there any known issues with the API?

**Comment by cclass** [comment]
Having the same issue

**Comment by cclass** [comment]
@3x14159265 if you haven't already figured this issue out, i think those URLs in the response are ever-present and don't necessarily indicate an error. After troubleshooting, the issue appears to be the array format I was sending but once I got that correct (and the data updated in Intercom) I would see get the response with the error link.

**Comment by choran** [comment]
Hi @3x14159265 
I am just checking if you are still having issue with this? As noted in the previous response the errors link is always present and provides a way to retrieve errors for your bulk jobs. If you are still having trouble submitting bulk jobs let us know and please re-open but I will close this in the meantime.
Thanks
Cathal
