### ISSUE TITLE
getLeads with created_since do not filter leads

### ISSUE THREAD

**Issue by mohsinrasool** [intercom/intercom-php#175]
## Version info
- intercom-php version: 2.0.0
- PHP version: 5.6.16
## Expected behavior

`$client->leads->getLeads(['created_since'=>2]);` Call should return filtered results that are about few hundred leads in my case.
## Actual behavior

`$client->leads->getLeads(['created_since'=>2]);` call returns over 4000 pages of 50 instances per page that are same as if I omit "created_since" parameter.

```
   [type] => contact.list
    [pages] => stdClass Object
        (
            [type] => pages
            [next] => https://api.intercom.io/contacts?created_since=2&per_page=50&page=2
            [page] => 1
            [per_page] => 50
            [total_pages] => 4072
        )
```
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
1. $client = new IntercomClient(PAT, null)
2. $client->leads->getLeads(['created_since'=>2]);

Am I missing something or it actually has some issues?

**Comment by mohsinrasool** [comment]
@Skaelv: Can you please respond to this as well?

**Comment by Skaelv** [comment]
You can do this for users but not for leads yet.
I'm adding this as a feature request for the team.

**Comment by mohsinrasool** [comment]
Any possible ETA, when it will be available?

**Comment by khalilovcmd** [comment]
hey @mohsinrasool , apologies for the late response. We have had a chat about this feature request, and I am sorry to say that it will be at least 2+ months till we start working on it. 

We will definitely update this issue once there is progress 👍

**Comment by mohsinrasool** [comment]
Thanks for the update. I will limit number of pages then.

**Comment by khalilovcmd** [comment]
I think that's a good way to go about it 👍
