### ISSUE TITLE
convertLead() call do not work as expected

### ISSUE THREAD

**Issue by mohsinrasool** [intercom/intercom-php#176]
## Version info
- intercom-php version: 2.0.0
- PHP version: 5.6.16
## Expected behavior

$leads->convertLead() call with both contact and user identifiers set should merge contact with user and delete the contact.
## Actual behavior

When $leads->convertLead() called with both contact and user identifiers set, creates a converted the contact to a new user. System then has two users with same email address.
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
1. $lead = $client->leads->getLead('8a88a590-e1c3-41e2-a502-e0649dbf721c');
2. $user = $client->users->getUsers(['email'=>$lead->email]);
3. $response = $client->leads->convertLead(array('contact'=>array('user_id'=>$lead->id), 'user'=>array('user_id'=>$user->user_id)));

Please, assume $contact and $lead exists (and are proper) and so point (3) looks something like following.

`$response = $client->leads->convertLead(array('contact'=>array('user_id'=>'8a88a590-e1c3-41e2-a502-e0649dbf721c'), 'user'=>array('user_id'=>'578d39cd1806525670000190")));`

$response should return a user object having user_id same as the 'user->user_id' passed to it but it returns a new user_id and adds a new user in the system.

**Comment by Skaelv** [comment]
Looking at this : 
```php
$lead = $client->leads->getLead('8a88a590-e1c3-41e2-a502-e0649dbf721c');
$contact = $client->users->getUsers(['email'=>$lead->email]);
$response = $client->leads->convertLead(array('contact'=>array('user_id'=>$lead->id), 'user'=>array('user_id'=>$user->user_id)));
```
It seems that you are creating a user with the `$contact` variable but you are trying to get the `user_id` from : `$user->user_id` which is probably `undefined`. 

Can you confirm this is not the code you are trying to run ?

**Comment by mohsinrasool** [comment]
Thanks Skaelv for responding. 

Yes, this is not the exact code I am using for production. But, following is the exact data (converted to JSON for visualization) I am sending to API

Following was passed to 'convertLead' function, both lead and users exists for sure. 
`{
  "contact":{"user_id":"04a79d96-1b23-4a3e-b8ec-78b51bced58d"},
  "user":{"user_id":"578d39cd1806525670000190"}
}`

Response I got from the convertLead is 
`{"type":"user","id":"578d3ccff254c513bc0004db","user_id":"578d39cd1806525670000190","anonymous":false,"email":"xxxxxxxxxxx@gmail.com","name":"Al","pseudonym":"Yellow Ghost","avatar":{"type":"avatar","image_url":null},"app_id":"ya6n12cx","companies":{"type":"company.list","companies":[]},"location_data":{},"last_request_at":null,"last_seen_ip":null,"created_at":1468873935,"remote_created_at":1476193775,"signed_up_at":1476193775,"updated_at":1476193775,"session_count":0,"social_profiles":{"type":"social_profile.list","social_profiles":[]},"unsubscribed_from_emails":false,"user_agent_data":null,"tags":{"type":"tag.list","tags":[{"type":"tag","id":"487271","name":"CSV Import - 2016-07-18 20:17:10 UTC"},{"type":"tag","id":"487291","name":"CSV Import - 2016-07-18 20:30:04 UTC"},{"type":"tag","id":"486978","name":"Fitness Newsletter"},{"type":"tag","id":"490877","name":"CSV Import - 2016-07-20 17:10:18 UTC"},{"type":"tag","id":"490897","name":"Healthy Lifestyle Newsletter"}]},"segments":{"type":"segment.list","segments":[{"type":"segment","id":"57dae1262ca23959639f196a"}]},"custom_attributes":{"country":"usa","city":"gardnerville","zip":null,"address1":null,"Email Preferences":"Daily Workout Email, Fitness, Weight Loss, Sex and Relationships, Lifestyle, Food and Recipe Emails, Health, Style and Fashion","Evergreen Bootcamp":null,"country_code":"US","province":null}}`

Okay, I just noticed that `user_id` is  same but why system has two Users of same name "AI". One user has "578d39cd1806525670000190" in User ID column and when opened has "578d3ccff254c513bc0004db" in URL. Other user has Unknown in User ID column and "578d39cd1806525670000190" in URL.

Am I missing anything here?

**Comment by mohsinrasool** [comment]
ReadMe file of this repo call convertLead like following

`// Convert a Lead to a User
$leads->convertLead([
  "contact" => [
    "user_id" => "8a88a590-e1c3-41e2-a502-e0649dbf721c"
  ],
  "user" => [
    "email" => "winstonsmith@truth.org"
  ]
]);`

However, the API Reference https://developers.intercom.com/reference#convert-a-lead has following syntax 
`$response = $intercom->convertContact([
  "contact" => array("user_id" => 1),
  "user" => array("user_id" => 2)
])`

Which one is correct?

**Comment by Skaelv** [comment]
https://github.com/intercom/intercom-php/blob/8689ad2f59728a9b99bf3f839adecbadd6c8e786/src/IntercomLeads.php#L78

`ConvertLead` is correct syntax. We are currently working on updating our docs sorry for the inconvenience.

**Comment by mohsinrasool** [comment]
Okay, thanks.

Now that I have over 100,000 duplicate users. Can you give an idea How can we merge the duplicate users?

**Comment by Skaelv** [comment]
So what happened here I guess is the following : 
```php
$leads->convertLead([ "contact" => [ "user_id" => "8a88a590-e1c3-41e2-a502-e0649dbf721c" ], "user" => [ "user_id" =>$user.id ] ]);
``` 

Notice the ` [ "user_id" =>$user.id ]` which should have been ` [ "user_id" =>$user.user_id ]`.
`user_id` and `id` are two different things. `id` is Intercom unique identifier whereas `user_id` is another identifier that customers can use as they want to.

What makes me think it is what happened is that your second duplicated user has what should be a  `user_id` in the url when all ids in Intercom platform Url are actually ids.
I know it's a bit confusing.
Concerning the 100,000 duplicate users you should contact our customer support directly.

**Comment by mohsinrasool** [comment]
Thanks for the insight. I will contact customer support.

Can you explain about the another issue I posted earlier as well @https://github.com/intercom/intercom-php/issues/175?
