### ISSUE TITLE
401 Unauthorized response on IntercomLeads::getLead connecting with personal access token

### ISSUE THREAD

**Issue by slumrig** [intercom/intercom-php#187]
## Version info
  - intercom-php version: 3.0
  - PHP version: 5.6.17

## Expected behavior
Connected to IntercomClient via intercom personal access token, calling IntercomLeads::getLead returns a known lead by id.
## Actual behavior
Connected to IntercomClient via intercom personal access token, calling IntercomLeads::getLead responds with 401 Unauthorized
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1.  Connecting with personal access token

> $connection = new IntercomClient(env('INTERCOM_ACCESS_TOKEN'), null);
> $lead_id = '5841d4a60f53ad6be0188bf7'; // existing lead
> $lead = $connection->leads->getLead($lead_id);

 2. Works connecting with an API Key:

> $connection = new IntercomClient(env('INTERCOM_APP_ID'), env('INTERCOM_API_KEY'));
>     $lead_id = '5841d4a60f53ad6be0188bf7'; // existing lead
>     $lead = $connection->leads->getLead($lead_id);

 
 3. 
From what I can trace in the code in IntercomClient.php line 228 it doesn't look like its been refactored to work with only a personal access token:

> public function getAuth()
>   {
>     return [$this->usernamePart, $this->passwordPart];
>   }

## Logs

> ClientException in RequestException.php line 107: Client error: `GET https://api.intercom.io/contacts/5841d4a60f53ad6be0188bf7` resulted in a `401 Unauthorized` response:
{"type":"error.list","request_id":"aoo62i6bv1cp1c690aeg","errors":[{"code":"token_unauthorized","message":"Not authorize (truncated...)

**Comment by mmartinic** [comment]
@slumrig This has been fixed on our API. You should be able to use `getLead ` now

**Comment by enisgultekin** [comment]
You told us the problem fixed it but I think ,won't be fixed. I got same error from your api, by email
