### ISSUE TITLE
401 Unauthorized response when using Personal Access Token on getSegments

### ISSUE THREAD

**Issue by marzsman** [intercom/intercom-php#189]
## Version info
  - intercom-php version: 3.1.0
  - PHP version: 5.6.11

## Expected behavior
Return a list of segments when using the Personal access token

## Actual behavior
The getSegments method works with the API key but when I use my new Personal access token I get a 401 Unauthorized error.

## Steps to reproduce
 1. Connecting with personal access token
`$client = new IntercomClient(INTERCOM_PERSONAL_ACCESS_TOKEN, null);`
 2. Request segments
`$client->segments->getSegments();`
 

## Logs
`Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: GET https://api.intercom.io/segments resulted in a 401 Unauthorized response: {"type":"error.list","request_id":"ap9kd71qdhqhagb4j8j0","errors":[{"code":"token_unauthorized","message":"Not authorize (truncated...) '`

**Comment by marzsman** [comment]
Any news on this error? Or am I doing something wrong?

**Comment by Skaelv** [comment]
You can only create segments with the basic personal access token.
Did you try to apply for upgraded personal access token access?

**Comment by liviooo** [comment]
Is an Extended Scope needed to see the list of the Segments ? The site is not clear about that:

Extended scopes

 Read and write users : List all users, create custom attributes and execute bulk actions
 Read and list users and companies : List and view all users and companies
 Read conversations : View conversations
 Read admins :  List and view all admins
 Manage webhooks : Create and update webhooks

**Comment by Skaelv** [comment]
We are actively working on improving the doc around personal access token. To list all segments extended scope is needed.

**Comment by liviooo** [comment]
OK... thank you for your reply !

**Comment by marzsman** [comment]
Ok thx, we submitted the upgrade request
