### ISSUE TITLE
Syntax Error doing anything

### ISSUE THREAD

**Issue by bgold0** [intercom/intercom-php#191]
This is what I have:

    use Intercom\IntercomClient;
    $INTERCOM_CLIENT = new IntercomClient("{O AUTH}", null);

    $INTERCOM_CLIENT->users->create(["user_id" => $uid, "email" => $email, "last_request_at" => time() ]);
```
<br />
<b>Parse error</b>:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in <b>/../vendor/intercom/intercom-php/src/IntercomClient.php</b> on line <b>7</b><br />
```

**Comment by smottt** [comment]
What's your PHP version?

**Comment by bgold0** [comment]
5.5 - I think i realized I needed a higher version so I had to resort to doing manual CURL requests.

**Comment by Skaelv** [comment]
This library supports php > 5.6. 

If you can't update your php version you might want to try this [unofficial intercom php](https://github.com/gayanhewa/intercomphp) library.

**Comment by nezaboravi** [comment]
I am having php 5.6 and getting the same error
php -v
PHP 5.6.30-11+deb.sury.org~trusty+3 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
