### ISSUE TITLE
problem with conversion tag object

### ISSUE THREAD

**Issue by hawksakr** [intercom/intercom-php#192]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

## Version info
  - intercom-php version: 4.0
  - PHP version: PHP 5.6

## Expected behavior
with the conversion Api  i should get tags list of conversion but it's alwayes none exist even iam sure that the conversion i check is tagged 
## Actual behavior
conversion tags object none exist 
## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1. $conv = $__intercom->conversations->getConversations(array(
                'type' => 'user',
                'email' => $email,
            ));
 2. echo json_encode($conv);

**Comment by choran** [comment]
Hi @hawksakr 
Sorry for the delay here, we are trying to to follow up on some older issue where there was no response previously. 
The format for some of the PHP operations has changed. If you go to the reference page you can get some examples there of common actions which might be useful, e.g. [listing conversations](https://developers.intercom.com/reference#list-conversations).
I dont think you can list conversations by tags, you can use ID, email, user_id and states such as whether the conversations are open or not. For example the below should work

If you try this it should work
```
<?php
$intercom->conversations->getConversations([
    "type" => "admin",
    "admin_id" => "891290",
    "open" => false
]);
?>
```
Alternatively, if you were listing conversations for a lead it would look something like this
```
<?php
$convs= $intercom->conversations->getConversations([
  "type" => "lead",
  "email" => $email,
  "open" => true
]);
var_dump($convs);
?>
```
Let me know if you are still having issues with this. I will close this issue for now but feel free to reopen if you still have any questions on this.
Thanks
Cathal
