### ISSUE TITLE
Is there an official changelog?

### ISSUE THREAD

**Issue by guilherme6191** [intercom/intercom-php#200]
Hey, guys. Great work!

I noticed that the changelog file within the code hasn't been updated in a while. I was wondering if there is another official changelog so we can keep updated about the new versions.

Thanks!

**Comment by Spriz** [comment]
I'm keeping up to date on the "releases": https://github.com/intercom/intercom-php/releases :-) Not sure if theres anything more offical though!

**Comment by guilherme6191** [comment]
Actually, this works fine. Thank you!
