### ISSUE TITLE
Configure Guzzle Requests Timeout

### ISSUE THREAD

**Issue by lucianocn** [intercom/intercom-php#205]
It would be a good practice to have an option to change the default Guzzle requests timeout (default is 0 - unlimited).

By the way, I can make the changes in the lib if it is okay.

- Connection timeout
http://docs.guzzlephp.org/en/latest/request-options.html#connect-timeout
- Response timeout
http://docs.guzzlephp.org/en/latest/request-options.html#timeout

**Comment by lucianocn** [comment]
Pull Request #206

**Comment by choran** [comment]
Hi @lucianocn 
Just following up here ... I see that there was an update on your #206. Did you get any chance to add tests for this? I will look through the PR as soon as I get a chance but just wanted to ping you in the meantime. Any examples for the README would be great as well. If not we can work on that.
Thanks
Cathal

**Comment by choran** [comment]
Merged #232 
Closing this issue as a result
