### ISSUE TITLE
Possible to lower the required PHP version to 5.5?

### ISSUE THREAD

**Issue by frankarensmeier** [intercom/intercom-php#211]
I notice on the Github page that the client needs PHP5.6. I am wondering if this can be downgraded to 5.5.

My servers are running under Ubuntu LTS 14 which comes with PHP5.5. Because those servers are production servers, I try to stay with the out-of-the-box setup as close as possible. I also do believe that both versions (Ubuntu and PHP) are still very common in the real world. As far as I can see, the only reason why the Intercom API might need PHP 5.6. is in Intercomclient.php on line 7:

```php
use function GuzzleHttp\Psr7\stream_for;
```

In order to make the client work under PHP 5.5, only two changes are necessary.
```diff
 use GuzzleHttp\Client;
 use GuzzleHttp\Psr7\Response;
-use function GuzzleHttp\Psr7\stream_for;
+use GuzzleHttp\Psr7;
 use Psr\Http\Message\ResponseInterface;
 
 class IntercomClient
@@ -199,7 +199,7 @@
      */
     private function handleResponse(Response $response)
     {
-        $stream = stream_for($response->getBody());
+        $stream = Psr7\stream_for($response->getBody());
         $data = json_decode($stream);
         return $data;
     }
```
Is there any reason not to lower the supported PHP version for the API client?

**Comment by Spriz** [comment]
Is there any reason not to run 5.5+? 

Check out http://php.net/supported-versions.php - the 5.5 is end-of-life!

**Comment by Skaelv** [comment]
Hi @frankarensmeier, I understand your problem here but I don't think we are comfortable downgrading the supported version for PHP. I recommend that you upgrade your servers to php5.6.
