### ISSUE TITLE
Get Lead events 

### ISSUE THREAD

**Issue by jimovi24** [intercom/intercom-php#213]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-php version: 2.0.0
  - PHP version: 7

## Expected behavior
Get Lead events

**Comment by apassant** [comment]
@jimovi24 Can you please add more details about the issue? Thanks.

**Comment by jimovi24** [comment]
I can only access the events that belong to a user but not a Lead, I can only create leads events

**Comment by choran** [comment]
Hi @jimovi24 
Can you provide some example code for this? You are able to submit events for both users and leads and also list events for users and leads so I would like to see what code you are using. That will help us understand where you are going wrong.
For example this should work to list events for a lead
```
$events = $intercom->events->getEvents(["intercom_user_id" => "5977303470ab1227b1abaa9fd"]);
foreach ($events->events as $event) {
    print "id:".$event->id." name:".$event->event_name."\n";
}
```

**Comment by choran** [comment]
Just closing this for now, but please re-open if you have an update on this or are still having an issue.
Thanks
Cathal
