### ISSUE TITLE
Delete users by email address

### ISSUE THREAD

**Issue by dominics** [intercom/intercom-php#217]
The client should support deleting users by email address, as it is supported from the API. However, because `IntercomUsers::deleteUser($id, $options)` always builds a path from the user ID, this isn't supported by this client (unless Intercom just ignore the trailing slash - but it's not good to have two URIs for the same resource in any case...)

Probably, this could be fixed by making `IntercomUsers::userPath()` not attach a trailing `/` if the ID passed is falsey

**Comment by dominics** [comment]
> Probably, this could be fixed by making IntercomUsers::userPath() not attach a trailing / if the ID passed is falsey

Nah, that won't work because `IntercomClient::delete()` doesn't allow access to the query parameters (it is `public function delete($endpoint, $json)`)

**Comment by choran** [comment]
Hi @dominics 
Thanks for this, sorry we didnt get a chance to look at this yet but we will try to get to the PR you submitted asap

**Comment by choran** [comment]
Just closing since we closed the PR.
