### ISSUE TITLE
Consider refactoring to PSR2

### ISSUE THREAD

**Issue by dominics** [intercom/intercom-php#218]
It'd be nice if this project used a consistent coding style so that contributors know how their code should be formatted.

At the moment, there are files using mixed 2 and 4 space indentation within the same file (ugh). And given the 2 space convention is rare in the PHP ecosystem (~6% of projects, c.f. 65% using 4 spaces), I'd wager you'll see those inconsistencies multiply over time. If you still want to use two-spaces, that's fine, but either way the choice should be consistently enforced.

You can drop a `phpcs.xml` in the root of the repo to get a `go fmt`-style convention (using `phpcbf`) where you can do all the formatting in CI.

**Comment by choran** [comment]
Hi @dominics 
Thanks for pointing this out. I will have to look into the option you suggested before making any changes. Just havent used it before. For now I will leave this open see if any other people in the PHP community have an opinion on this also. 
Thanks again
Cathal

**Comment by Spriz** [comment]
+1 to PSR2 - or at least any other defined standard with a phpcs config file :)

**Comment by choran** [comment]
Thanks for the update. We will take a look at this, at the moment it is probably not on the main list of changes we want to make to our SDKs, e.g. feature updates and PR reviews are focus at the moment, but we will keep it in mind for future updates

**Comment by kmossco** [comment]
Hey @dominics and @Spriz, I definitely agree that the project should follow the PSR-2 coding style guidelines, and thank you so much for flagging this! I have kickstarted the slow process of converting it, and started with the whitespacing, commenting and indenting rules here: #233. I think this is a good start, and I'll leave it up to @choran to decide what parts of the convention the project should follow next.

It is a big change, and I did my best to test this as thoroughly as possible, but an extra set of 👀 wouldn't hurt. 😉

**Comment by choran** [comment]
Thanks @kmossco for this ... will review and approve asap 👍

**Comment by choran** [comment]
@dominics @Spriz @kmossco Thanks for all the work here.
I finally got a chance to review the changes and have just merged them in there.
I just need to remember to follow this format myself in future when making any changes!
I was going to close this issue now that some of the items have been addressed?
If you think it is better to leave this open let me know. 
If there are other specifics we need to address we could open another separate issues for those instead?

**Comment by Spriz** [comment]
@choran which code editor are you using? Most popular modern editors can do 99% of this automatically :)

**Comment by choran** [comment]
@Spriz you mean 99% of the indenting type formatting or of PSR-2 convention in general?
This was addressing the mixed indentation issues noted above.
I wasnt sure what other areas people felt we should focus on now for PSR-2?

**Comment by Spriz** [comment]
I meant that 99% of the PSR2 rules will be enforced my most modern editors/IDE with plugins etc :D

**Comment by choran** [comment]
Cool 👍  
yeah, I think they should cover most issues like that.
Just wasnt sure if there were some other things we should address in this issue.
It doesnt look like it so I might close this issue for now unless anyone else thinks we should keep it open.
Thanks
Cathal

**Comment by choran** [comment]
@Spriz  Just closing this since the PR has been merged in
As always, feel free to open a new PR/issue for any other suggested changes
thanks 👍
