### ISSUE TITLE
Get a single segment by ID

### ISSUE THREAD

**Issue by dominics** [intercom/intercom-php#219]
The client is missing the endpoint described at https://developers.intercom.com/v2.0/reference#view-a-segment - viz. `https://api.intercom.io/segments/{id}` - to retrieve a single segment via ID (with optional counts)

**Comment by choran** [comment]
Hi @dominics 
Thanks for submitting this, we will be reviewing all the PHP PRs shortly to be able to take an action on them. So should get to this soon. Thanks and appreciate taking the time to submit this.
Cathal
