### ISSUE TITLE
Provide an easy way of getting at the rate limit response headers

### ISSUE THREAD

**Issue by dominics** [intercom/intercom-php#223]
Because the client doesn't allow callers access to the underlying PSR7 response, it's not easy to get information about the current state of the rate limiter. Specifically, there doesn't seem to be a way to access the rate limiting headers (`X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`) other than writing your own Guzzle 6 middleware, and attaching it to an injected client.

One way of handling this might be to make `IntercomClient::handleResponse($response)` take note of any rate limiting headers and save them on its instance. Then you'd just need a getter to get the most recent set. (That's [what the Ruby bindings do](https://github.com/intercom/intercom-ruby/blob/bd3083b0a903bc0df12baeb1d8e4ad4ae69ef425/lib/intercom/request.rb#L68))

**Comment by choran** [comment]
Hi @dominics 
Thanks again, I see you have submitted a number of PRs. As I noted in the other issues you opened we will take a look at all of these shortly and take an action on them.
Thanks
Cathal
