### ISSUE TITLE
Bulk API broken link

### ISSUE THREAD

**Issue by egyptik** [intercom/intercom-php#226]
Trying to use the users bulk API, resulting in a 422. That issue is described below, but I just want to point out that the link to the documentation that's mentioned in the comments at the  `Intercom\IntercomBulk` class is broken (https://developers.intercom.io/reference#bulk-user-operations). Can't find new documentation anywhere on the dev site..

## Version info
  - intercom-php version: 3.1.3
  - PHP version: 7.1.0

## Expected behavior
Sending an array of user profiles to create/update profiles in bulk. Expecting successful 202 response from the API.

```php
$intercom->bulk->users($array_of_profiles_to_update);
```

## Actual behavior
Results in HTTP 422. Updating the profiles works perfectly fine when looping over the array and calling the non-bulk create/update method:

```php
foreach($array_of_profiles_to_update as $profile_to_update)
{
    $intercom->users->create($profile_to_update) // 200 response
}
```

This method, of course, is slow and resource intensive so I'd rather use the bulk method. Any ideas?

**Comment by choran** [comment]
Hi @egyptik 
We are currently reviewing our bulk endpoint internally to decide how best to move forward. At the moment it does not offer any benefit over using the regular API so we have removed all reference to it from our dev docs. We will still continue to support it but are encouraging users to migrate to using the regular API instead. We will provide updates once we conclude our internal review and decide how to move forward with bulk.
So for now I will close this issue as it relates to bulk, we will not be making any changes until we identify the best way to move forward with our bulk approach.
Thanks
Cathal

**Comment by egyptik** [comment]
Okay, thanks Cathal!

**Comment by mattnetto** [comment]
@choran is there any update about it?
