### ISSUE TITLE
Error, when trying install via composer

### ISSUE THREAD

**Issue by compman56** [intercom/intercom-php#244]
**Getting next error, when trying install via composer** (after command "php composer.phar require intercom/intercom-php"):

> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - The requested package intercom/intercom-php No version set (parsed as 1.0.0) is satisfiable by intercom/intercom-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

## Version info
  - intercom-php version: latest from github
  - PHP version: 7.1.7

**Comment by kmossco** [comment]
Hey @compman56 I just tested this on my end, and it seemed to work correctly:

```bash
~/k | λ  curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer (version 1.6.2) successfully installed to: /Users/bruno/k/composer.phar
Use it: php composer.phar

~/k | λ  php composer.phar require intercom/intercom-php
Using version ^3.1 for intercom/intercom-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing intercom/intercom-php (v3.1.8): Downloading (100%)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files

~/k | λ  php -v
PHP 7.1.10 (cli) (built: Oct  6 2017 01:08:19) ( NTS )
```

Is this only happening in PHP 7.1.7 for you? Or also in other PHP versions?

**Comment by choran** [comment]
@compman56 I was just wondering if you were still experiencing issues trying to install via composer?

**Comment by compman56** [comment]
Hello @choran and @kmossco ! 
Thanks for your replies!
I managed to install. Don't remember how I did it, but all ok now :)

**Comment by kmossco** [comment]
Considering you are back on track, closing this one for now. Please reopen if you continue to bump into any issues. 👍
