### ISSUE TITLE
(Request/Question) Add perma delete?

### ISSUE THREAD

**Issue by feedmeastraycat** [intercom/intercom-php#249]
Is there any plans to add the perma delete function to the lib? And not just have the archive call. 

Maybe create a new `$intercom->users->archiveUser("abc...")` but keep `$intercom->users->deleteUser("abc...")` as a alias and then creating a new `$intercom->users->permanentlyDeleteUser("abc...")`. This way it would not confuse anyone or break anything.

**Comment by kmossco** [comment]
We are currently going through all the different repos to make sure they have feature parity with the available API methods, so I am sure we will add this soon. 👍 In the mean time, if anyone is willing, we are happy to review a PR as well!

**Comment by feedmeastraycat** [comment]
@kmossco Cheers. Sounds good. And if I get any extra time I will look into it.

**Comment by choran** [comment]
This should now be available in #251
