### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by anantwaykar** [intercom/intercom-php#250]
After installing getting below error , can anybody tell me how to solve this.

Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /var/www/html/intercom/vendor/intercom/intercom-php/src/IntercomClient.php on line 7

**Comment by kmossco** [comment]
@anantwaykar can you check if you have at least PHP 5.6? Because that usually is an error that occurs in old PHP versions that don't accept anonymous functions.

**Comment by GabrielAnca** [comment]
Hi @anantwaykar 👋

I have just found other issue that describes exactly the same behaviour that you reported: https://github.com/intercom/intercom-php/issues/210.

As @kmossco mentions, it seems you are running a PHP version under 5.6.

As described [in the PHP documentation](http://php.net/manual/en/language.namespaces.importing.php), the aliasing of functions (`use function ...`), which is the one erroring in your case, is only supported in PHP5.6 onwards.

Please upgrade your version to at least PHP 5.6 and let us know if you still have any issue 😃
