### ISSUE TITLE
Not able to fetch all getUsers data... single user data are showing properly

### ISSUE THREAD

**Issue by siddharthundare** [intercom/intercom-php#257]
## Version info
  - intercom-php version:  v3.2.0 
- PHP version:  PHP 7.0.30-0ubuntu0.16.04.1 

#code
require 'vendor/autoload.php';
use Intercom\IntercomClient;

$client = new IntercomClient('ACCESS TOKEN', null);

try
{
    $users = $client->users->getUsers([]);
} catch (Exception $exc)
{
       print_r($exc->getMessage());
}

## Logs
Client error: `GET https://api.intercom.io/users` resulted in a `401 Unauthorized` response:
{"type":"error.list","request_id":"b4lgfoceq2b4v78dj4k0","errors":[{"code":"token_unauthorized","message":"Not authorize (truncated...)

**Comment by siddharthundare** [comment]
Problem solved this kind of issue is occurred when you don't have Standard + extended scopes permissions.

**Comment by GabrielAnca** [comment]
Hey @siddharthundare 👋 Thanks a lot for opening the issue and for sharing the solution with us. Indeed, you'll need those scopes to make that call.

I see the fact that the error message is truncated is also part of the problem, as no specific message is displayed apart from `Not authorized`.

I'll close this issue and we can continue the discussion about the truncated error message in https://github.com/intercom/intercom-php/issues/237.
