### ISSUE TITLE
Getting error "code":"400","message":"User email, user_id or anonymous_id must be supplied"

### ISSUE THREAD

**Issue by avikesari** [intercom/intercom-php#267]
I want to update custom_attributes through PHP CURL.  
This is my code

try {
                    $postData = json_encode(array(
                        "user_id" => strval($userId),
                        "email" => $userEmail,
                        "custom_attributes" => ['unsubscribed_from_emails' => 'true']
                    ));

                    $postHeader = [
                        'Authorization: Bearer <Access Token>',
                        'Accept: application/json',
                        'Content-Type: application/json -d'
                    ];
                    error_log("post data" . $postData);

                    $curl = curl_init("https://api.intercom.io/users");
                    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
                    curl_setopt($curl, CURLOPT_POSTFIELDS, $postData);
                    curl_setopt($curl, CURLOPT_RETURNTRANSFER, FALSE);
                    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
                    curl_setopt($curl, CURLOPT_HTTPHEADER, $postHeader);
                    error_log("curl data" . $curl);
                    curl_exec($curl);
                    curl_close($curl);
                } catch (Exception $e) {
                    error_log($e->getMessage());
                } 

I am passing user_id and email as parameter still getting this error.
{"code":"400","message":"User email, user_id or anonymous_id must be supplied"}

## Version info
  - intercom-php version:
  - PHP version:

## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1. 
 2. 
 3.

**Comment by GabrielAnca** [comment]
Hi @avikesari 👋 

Thank you for sharing that issue with us. However, this repository is meant to report issues about our PHP SDK. For general API issues, please visit our [developer forum](https://community.intercom.com/).

I would say the error is that the `Content-Type` header you're sending is invalid, whichresults in our application not being able to understand your request. Please try sending `'Content-Type: application/json'` instead.
