### ISSUE TITLE
Scroll for companies [Feature request]

### ISSUE THREAD

**Issue by petemcfarlane** [intercom/intercom-php#277]
It'd be great if you could add a scroll to the IntercomCompanies, much like there is for users and leads. Any plans to add this, or would you welcome a PR?

**Comment by GabrielAnca** [comment]
Hi @petemcfarlane 👋 At the moment adding this feature to this SDK is not in our roadmap, but we'd be very happy if you are willing to contribute with this feature, a PR will be very welcome!

**Comment by petemcfarlane** [comment]
Sorry @GabrielAnca I found an alternative solution to my problem, so never needed to build this patch, and I don't have time right now to contribute a PR. I'll let you decide whether to leave the feature request open for someone else to build or feel free to close if it's not a priority. Thanks

**Comment by GabrielAnca** [comment]
Thanks for your message! We don't usually keep feature request issues open, but we'll be happy to review if anybody wants or needs to implement the feature 😃
