### ISSUE TITLE
leads->convertLead() not working as per docs

### ISSUE THREAD

**Issue by tillkruss** [intercom/intercom-php#283]
I'm looking at this page: https://developers.intercom.com/intercom-api-reference/reference#convert-a-lead

The PHP examples states:

```php
$intercom->leads->convertLead([
    "contact" => [
        "id" => "596f6b60d797879302bd7ac1" 
    ],
    "user" => [
        "user_id" => "470" 
    ]
]);
```

However, I get a "Bad Request" when calling the method that way.

This seems to work:

```php
$this->client->leads->convertLead([
    'contact' => ['id' => '596f6b60d797879302bd7ac1],
    'user' => ['email' => 'user@email.com'],
]);
```

That's not ideal, because if the user changes their email address our job work properly.

Is there any way to call the endpoint with a `user_id` instead of an email?

**Comment by GabrielAnca** [comment]
Hi @tillkruss 👋 

I've flagged the error in the documentation and the change has gone live, so you can see the updated docs with the same link you shared 😃 Thanks for sharing that with us!

Regarding your question, I don't have enough context on the leads endpoints to provide you with a meaningful answer as it is not SDK-related. I'd recommend you to ask that question in the [community forum](https://community.intercom.com/c/building-apps/rest-apis) or in [the API reference](https://developers.intercom.com/intercom-api-reference/reference#convert-a-lead) via the Intercom messenger. That way you'll find the people with the right context and we'll be able to register a feature request if that's not possible at the moment.

As the question is not related to the SDK but to the API instead, I'll close this issue, but feel free to reach out if you have any further questions 😃
