### ISSUE TITLE
Can't Retrieve Multiple Users by Email

### ISSUE THREAD

**Issue by danlafreniere** [intercom/intercom-php#289]
Hey guys! For our purposes, it'd be really helpful to be able to retrieve multiple users by email. I'm logging it as an issue but I suppose it's more of a feature request. I just wanted this out there - I've read about it in other intercom modules but not the php one.

## Version info
  - intercom-php version: 4.0.2
  - PHP version: 7.2.20

## Expected behavior
API returns an array of users with the matching email.

## Actual behavior
API throws conflict error.

## Steps to reproduce
 1. GET request to API using: $client->users->getUsers(["email" => "email@example.com"]);

## Logs
```
{
    "type": "error.list",
    "request_id": "0002mtll0fnt9s5aigpg",
    "errors": [
        {
            "code": "conflict",
            "message": "Multiple existing users match this email address email@example.com - must be more specific using user_id"
        }
    ]
}
```

**Comment by GabrielAnca** [comment]
Hi @danlafreniere 👋 Thanks for sharing that issue with us. That behaviour has already changed in a newer version of the API. Please see https://github.com/intercom/intercom-php/issues/273#issuecomment-465935593 for more detailed information about how to use a newer API version 😄
