### ISSUE TITLE
Support for getting teams

### ISSUE THREAD

**Issue by dvaeversted** [intercom/intercom-php#300]
It is currently not possible to grab teams (https://developers.intercom.com/intercom-api-reference/reference#list-teams) through the SDK

**Comment by GabrielAnca** [comment]
Hi @dvaeversted we don't have a timeline on adding support for teams at the moment. However, we are open if you have time for it and want to give it a shot 😃

**Comment by lloydliyu** [comment]
Added in https://github.com/intercom/intercom-php/pull/305. Closing.
