### ISSUE TITLE
Conversation rating

### ISSUE THREAD

**Issue by devmsh** [intercom/intercom-php#303]
I read the whole API for every version, and did not find any possibility to rate a conversation through the rest API.

Is there any undocumented `message_type` that can fix this limitation, because the UI already allowed to do that?

**Comment by lloydliyu** [comment]
Hey @devmsh :wave:

The SDK can only do what the Intercom Public REST API is capable of and nothing more and currently the Intercom API doesn't support this. It sounds like a great idea and I'd definitely recommend letting the support team know you'd like to see this within the API. You can let them know using the Messenger on https://intercom.com 

As this isn't an issue with the SDK specifically, I'm going to close this out.
