### ISSUE TITLE
Unable to catch exception when creating client

### ISSUE THREAD

**Issue by kevindeleon** [intercom/intercom-php#310]
I'm attempting to wrap the new client request in a try/catch so that I might catch any exceptions when creating the client (should someone remove the app, should the access token accidentally get changed, etc). I thought perhaps I needed to use `Http\Client\Common\Exception\ClientErrorException` instead of `Http\Client\Exception` -- but that didn't work either. I'm sure this is something completely silly that I'm overlooking here.

## Version info
  - intercom-php version: 1.4
  - Intercom API version: 4.3
  - PHP version: 7.2.4

## Expected behavior

Would expect to receive an error object that I could then evaluate.

## Actual behavior

PHP Uncaught exception:

Fatal error: Uncaught Http\Client\Common\Exception\ClientErrorException: Unauthorized in /path/to/app/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:83 Stack trace: #0 /path/to/app/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(65): Http\Client\Common\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /path/to/app/endor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(31): Http\Client\Common\Plugin\ErrorPlugin->Http\Client\Common\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response)) #2/path/to/app/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(66): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure)) #3 /path/to/app/vendor/php-http/client-common/src/PluginChain.php(48): Http\Client\Common\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Http\Client\Common\PluginChain)) #4 /path/to/app/vendor/php-http/client-common/src/PluginChain.php(63): Http\Client\C in /path/to/app/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php on line 83

## Steps to reproduce (as granular as possible, including screenshots where appropriate)
```
try {
    $client = new IntercomClient('invalidaccesstokenheretothrowerror');
} catch (Http\Client\Exception $e) {
    var_dump($e);
}
```

**Comment by kevindeleon** [comment]
Never mind. This was a name spacing issue. Adding a "\" in front of "Http" seems to have solved this for me.

**Comment by GabrielAnca** [comment]
Hi @kevindeleon I was about to mention that the code you shared shouldn't raise any exception because it's not making any api call. You'll get the exception the first time the sdk tries to fire an api call.

If you make a request inside of the try-catch block, ie:

```php
    try {
      $client = new IntercomClient('asdasdsad');
      $client->contacts->getContacts([]);
    } catch (\Http\Client\Exception$e) {
      var_dump(get_class($e));
    }
```

You should then get an exception of type `Http\Client\Common\Exception\ClientErrorException`

**Comment by kevindeleon** [comment]
Hey @GabrielAnca -- right...I was making the call...I must have copied and pasted an old bit of code that had the call removed...sorry about that...but yeah...anyway...all sorted now 👍
