### ISSUE TITLE
Laravel 8 requires Guzzle 7.0.1

### ISSUE THREAD

**Issue by patrickomeara** [intercom/intercom-php#317]
The minimum Guzzle requirement for Laravel 8, is Guzzle 7.0.1

There is no installable set, see below

## Steps to reproduce (as granular as possible, including screenshots where appropriate)

```
composer global require laravel/installer
laravel new laravel8 && cd laravel8
composer require intercom/intercom-php php-http/guzzle6-adapter
```

## Logs

```
 Problem 1
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[2.x-dev, v2.0.0, v2.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].
```

**Comment by GabrielAnca** [comment]
Hi @patrickomeara 👋 It seems there is no support for Guzzle 7 in HTTPlug at the moment.

Luckily this should not be a problem, I think you should be able to use intercom-php with a different HTTP client, for example cURL:

`composer require intercom/intercom-php php-http/curl-client`

**Comment by patrickomeara** [comment]
Thanks so much @GabrielAnca that worked a treat.

**Comment by baj84** [comment]
Hi @patrickomeara and @GabrielAnca do I need to do anything to tell intercom-php to use the curl client instead of guzzle?

**Comment by patrickomeara** [comment]
Hi @baj84 You shouldn't need to do anything special after requiring `php-http/curl-client` 

Do you have an error you can share?

**Comment by baj84** [comment]
@patrickomeara I was getting a 502 Bad gateway error, but this was due to malformed post request. It's all good now - thanks for your reply.
