### ISSUE TITLE
Exceptions does not provide exception body

### ISSUE THREAD

**Issue by SebastianMueller87** [intercom/intercom-php#343]
## Version info
  - intercom-php version: 4.4.2
  - Intercom API version: 2.3
  - PHP version: 7.4.x

## Expected behavior

- Access the body of API-Errors.

## Actual behavior

F.e.: 
Intercom returns an error response when you try to create a contact which already exists. 
This error gets converted to an `ClientErrorException` with status code `409` and reason phrase `Conflict`. 

The Body of the returned error can not be accessed. It contains very important informations, in this case the intercom id.(https://developers.intercom.com/intercom-api-reference/reference#create-contact)

## Steps to reproduce (as granular as possible, including screenshots where appropriate)

 1.  Create a contact via API
 2. Create the same contact again via API
 3. Inspect the Exception

**Comment by eexit** [comment]
Hey, do you use any middlewares?

**Comment by SebastianMueller87** [comment]
This issue is very old and we do not use intercom anymore. So it can be closed.
