### ISSUE TITLE
Unauthorized error when creating messages

### ISSUE THREAD

**Issue by driesvints** [intercom/intercom-php#54]
Hi, I'm sending a message from a user by using the example from the docs in the readme but I'm getting unauthorized exceptions the entire time.

```
Client error response [status code] 401 [reason phrase] Unauthorized [url] https://api.intercom.io/messages
```

I'm using the exact same example as the one from the docs. Both appid and appkey are set correctly. Any idea what might be wrong with the library?

**Comment by artizco** [comment]
Hi, I faced with the same problem. Could you help me pls?

**Comment by josler** [comment]
Hi @artizco,

Could you please contact me through Intercom about this? Thanks.

**Comment by wouterds** [comment]
Would be helpful to post the solution here and not in PM
