### ISSUE TITLE
Bulk requests

### ISSUE THREAD

**Issue by drewbroadley** [intercom/intercom-php#63]
It would be great to allow for bulk requests to the API through this client. The reason I say this, is being in NZ/AU, it's quite demanding of a user to wait 2-3 seconds while all I do is the following:

Update user
Tag User
Record Event

**Comment by stephenwf** [comment]
If you are having problems with load times, unless you are using the Intercom to persist your user data (unlikely?) I would recommend closing your connection to the client and then proceeding with the API call. To avoid causing multiple transactions chuck a lock into the session to tell subsequent connections to wait. 

Regarding reducing latency, it would be nice to post the tags along with the user on creation.

**Comment by bobjflong** [comment]
We have no plans right now to add new bulk endpoints beyond what we  currently offer: https://doc.intercom.io/api/#bulk-user-creation

Generally we recommend that Intercom actions are done async as suggested by @everdaniel
