### ISSUE TITLE
Upgrade to Guzzle 4.x or 5.x

### ISSUE THREAD

**Issue by borfast** [intercom/intercom-php#67]
Just what the title says :)

Guzzle is already at version 5.1.0, with 3.9 (the version currently used in Intercom) having been released almost a year ago, which makes it hard for people to keep up.

We use Guzzle 4.0 for our application and were able to install Intercom's package when it still required 4.0 but suddenly you downgraded it to 3.8 and now we're stuck, without being able to upgrade Intercom :(

**Comment by borfast** [comment]
Not even a "no"? :(

**Comment by eugeneius** [comment]
We never released a version of this library that requires Guzzle 4.0; the dependency was changed to Guzzle 3.9 in April (https://github.com/intercom/intercom-php/commit/7b1072da219cee3d512fb6633aa9ece26c2f74c4), and the first version was released in September ([v1.0.0-b1](https://github.com/intercom/intercom-php/releases/tag/v1.0.0-b1)).

How did you manage to install a version that requires Guzzle 4.0?

Also, according to the author of Guzzle, [Guzzle 3 and Guzzle 4 can be used simultaneously](http://mtdowling.com/blog/2014/03/29/guzzle4/):

> Because Guzzle 4.x was basically a rewrite of the library, I’ve updated Guzzle 4 to use a different namespace and a different Composer package name so that you can use Guzzle 3 and 4 in the same project and slowly migrate pieces of you applications over time as needed.

What's preventing you from installing the latest version of this library? What does Composer say when you try to update?

I agree that we should upgrade to a newer version of Guzzle by the way, but I don't think using it should be blocking you from using the latest version of this library.

**Comment by borfast** [comment]
@eugeneius, the diff from that exact commit you mentioned (7b1072d) shows `"guzzlehttp/guzzle": "~4.0"` was in `composer.json` before the change, and it was removed in favor of Guzzle 3.8 (not 3.9, that was a bit later in the same day, in f20275f). But it doesn't really matter :)

I know Guzzle 3 and 4 can be used simultaneously but that doesn't seem to be the problem. I should have explained this better, sorry.

We have `"guzzlehttp/guzzle": "4.0.2",` in our application and Intercom's package has `"guzzle/guzzle": "~3.9"`, so in theory it should be fine, but then we get this from Composer:

```
[Composer\DependencyResolver\SolverProblemsException]                                                                 
    Problem 1                                                                                                           
      - guzzle/guzzle 3.9.x-dev requires symfony/event-dispatcher ~2.1 -> no matching package found.                    
      - intercom/intercom-php dev-master requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[3.9.x-dev].        
      - Installation request for intercom/intercom-php dev-master -> satisfiable by intercom/intercom-php[dev-master].
```

As usual, this is next to useless in figuring out where the version mismatch occurs.

**Comment by eugeneius** [comment]
That looks like another dependency of your app require a conflicting version of `symfony/event-dispatcher`. What's the output of `composer depends symfony/event-dispatcher`?

**Comment by borfast** [comment]
Here it is:
```
$ composer depends symfony/event-dispatcher
guzzle/guzzle requires symfony/event-dispatcher (~2.1)
symfony/console requires (dev) symfony/event-dispatcher (~2.1)
symfony/http-kernel requires symfony/event-dispatcher (~2.5.9|~2.6,>=2.6.2)
symfony/security-core requires (dev) symfony/event-dispatcher (~2.1)
```

**Comment by borfast** [comment]
For some reason I had not yet tried what I usually do when I encounter one of these seemingly illogical Composer errors: delete the `vendor` directory and run `composer install` again. I just did that and it worked; everything was installed correctly... :|

**Comment by eugeneius** [comment]
Good to hear you solved your problem! :+1: 

We'll upgrade Guzzle before releasing the final v1.0.0 of this library.

**Comment by borfast** [comment]
Great, good to know that! :)

Thanks again, Eugene!

**Comment by timgws** [comment]
@bobjflong any word on when a migration to `guzzle/guzzle-services` might be in play? Guzzle 3 is EOL, and will no longer be supported by the end of the year.

> Guzzle 3 is only maintained for bug and security fixes. Guzzle 3 will be EOL at some point in late 2015.
>  - https://github.com/guzzle/guzzle3#this-is-an-old-version-of-guzzle

**Comment by bobjflong** [comment]
Thanks @timgws it's on my radar. I've no concrete timeline yet though :(

**Comment by nikkow** [comment]
+1 

Would be great to have an updated version using the latest Guzzle available. The current -deprecated- version requires symfony/event-dispatcher v2.x, which is currently not compatible with Symfony v3.

**Comment by mrj0909** [comment]
after calling api for fetch the user, I am unable to parse the data as it is coming in procect form like the below. So please guide me so that I can utilize it
object(Guzzle\Service\Resource\Model)#1400 (2) {
  ["structure":protected]=>
  NULL
  ["data":protected]=>
  array(7) {
    ["type"]=>
    string(9) "user.list"
    ["pages"]=>
    array(5) {
      ["type"]=>
      string(5) "pages"

**Comment by josephnle** [comment]
+1 Would be nice to have the library use the latest version of Guzzle so it can play nice with the rest of my application :)

**Comment by kyranb** [comment]
@bobjflong Any update on this?

**Comment by kyranb** [comment]
@eugeneius @bobjflong Any update on this?

**Comment by bobjflong** [comment]
Hi @kyranb - we don't have an estimate of when someone will get to this yet :(

**Comment by kyranb** [comment]
@bobjflong Thanks for the heads up :+1: 

I guess PHP is the sad ugly duckling around the office then! I hope you guys can find a way to share some of the love that the ruby library receives :smile:

**Comment by bobjflong** [comment]
Unless I'm missing something the upgrade guide does not provide much help for porting tests from 3.9 to 4: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

Step 0 is porting the tests. This looks like a major rewrite (unless I'm missing something). But doing so will hurt our ability to catch regressions.

**Comment by wavyx** [comment]
Hi,
Is anyone working on this ?
Do I miss something or it's only about fixing the "client" class ?

**Comment by bobjflong** [comment]
I've reached out to Guzzle: https://gitter.im/guzzle/guzzle

I'm trying to develop a plan that would let us migrate, but I don't see how it's possible until we can safely ensure no regressions occur. Right now both app code + tests need to be rewritten afaict. I hope I'm missing something.

**Comment by kyranb** [comment]
@bobjflong Can the current release be kept as stable with an unstable `2.0` release?

The instructions in the Read Me say to require `"intercom/intercom-php": "1.5.0"` so most users would need to update their composer file to receive the new version and  it would be expected that there are major differences.

**Comment by bobjflong** [comment]
Differences are absolutely fine, I just don't want to introduce a string of bugs. However if necessary we will just do it. Really unfortunate that it's looking like a major rewrite, and this is influencing my thoughts on whether we should use Guzzle at all!

**Comment by kyranb** [comment]
If the tests can't be upgraded easily, a rewrite would be the way to go. As for not using Guzzle the current version is v6 and v3 only reached end of life quite recently. If there's a package that's designed to be robust and reliable Guzzle is it.

If you opted not to use it, development would take a whole lot longer, you'd miss out on helpful error messages, add plenty of boilerplate code and probably introduce a slew of bugs as well. I say take on the rewrite 🎉  (if migrating the tests first isn't a viable option)

**Comment by wavyx** [comment]
Ok, so I had a quick look and indeed Guzzle changed a lot.
From what I get from the initial approach, we'll need:
- https://github.com/guzzle/guzzle-services to handle web services from a configuration
- https://github.com/gimler/guzzle-description-loader to load the description from the json files
- migrate IntercomTestCase to use the new Handler + History Middleware  http://docs.guzzlephp.org/en/latest/testing.html (and remove GuzzleTestCase https://github.com/guzzle/guzzle/blob/v3.8.1/tests/Guzzle/Tests/GuzzleTestCase.php)

The guzzle-description-loader is probably not mandatory and not working with Guzzle 6.2
The first step is probably to make "guzzle-services" work by fixing IntercomAbstractClient which should extends GuzzleClient from "guzzle-services"

**Comment by bobjflong** [comment]
In terms of maintainability I think I would prefer a thinner client, so that things like this don't happen in the future. I'll continue to think about this, and appreciate all of your input

**Comment by wavyx** [comment]
Guzzle 6 is indeed a very light/thin client (and very popular)
But your code heavily rely on the "web services by configuration" abstraction.
The GuzzleTestCase itself can probably be migrated to History Middleware.

IMHO, this leaves out 2 main options:
- Refactor code to use the new dependencies I mentioned and loading services from json as before
- Rewrite client and implement web services method instead of loading them fro json

**Comment by kyranb** [comment]
One other thing of note, whereas previously Guzzle had a lot of major changes, as of V6 Guzzle that wil be a lot less likely as it now adheres to [PSR-7](http://www.php-fig.org/psr/psr-7/).

**Comment by bobjflong** [comment]
Started a skeleton project here (using Guzzle 6): https://github.com/intercom/intercom-php-rewrite

My goal for the rewrite is to keep it pretty thin (like intercom-node) so that we are less affected by dependency & API changes.

Once it has sufficient functionality I'll probably reuse this repo and release as a new major version

**Comment by bobjflong** [comment]
Also, please vote for the resources you used to be added first 😄

**Comment by kyranb** [comment]
Super glad to see this coming together Bob! 

Here's my vote for resources (in order of priority)

1. Users
2. Events
3. Companies
4. Conversations

**Comment by bobjflong** [comment]
https://github.com/intercom/intercom-php-rewrite now has rudimentary support for Users, Leads, Events, Companies, Messages, and Conversations. It's extremely thin, and returns Guzzle responses. Please do give it a try!

**Comment by wavyx** [comment]
Hi @bobjflong,

I mainly use create/update/tag users and create events.
I agree on the order of @kyranb  Users > Events > Companies
I don't use the api to manage conversations.

Would be nice to be able to import with "composer require intercom/intercom-php-rewrite"

**Comment by bobjflong** [comment]
@wavyx cool - you should be able to get started immediately if you want to provide any feedback. You can point composer at the git repo if you like: https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by bobjflong** [comment]
https://github.com/intercom/intercom-php-rewrite is now feature complete! Please try it out!

**Comment by timgws** [comment]
yay! thanks @bobjflong
