### ISSUE TITLE
Problem during creating events

### ISSUE THREAD

**Issue by dbhattacharjee** [intercom/intercom-php#72]
Hi,
I am trying to integrate intercom with our symfony app and I am using following code:
public function addPackageCheckOutEvent($user, $package) {
  $intercomUser = 'XXXXXX';
 $metadata = array(
   "checout_date" => $package->getCheckedOut()->getTimestamp(),
   "tracking_code" => $package->getTrackingCode()
 );
 $this->intercomHandler->createEvent(array(
    "event_name" => "checkout-package",
    "created_at" => $package->getCheckedOut()->getTimestamp(),
    "id" => $intercomUser['id'],
    "metadata" => $metadata
 ));
} 
When this method executes, server is responding in below manner : 
{
"code": 500,
"message": "Client error response\n[status code] 400\n[reason phrase] Bad Request\n[url] https://api.intercom.io/events"
}

Any idea what is going wrong ?

**Comment by josler** [comment]
Hi @dbhattacharjee 

The events API does not support passing `"id"` as an identifier; sending `"user_id"` or `"email"` should do the trick.

http://doc.intercom.io/api/?php#submitting-events

Thanks!
