### ISSUE TITLE
Updating a user without specifying 'id'

### ISSUE THREAD

**Issue by rb-cohen** [intercom/intercom-php#73]
Is id a required field for updateUser, or would it be OK if I update the service config?

My interpretation of the docs at http://doc.intercom.io/api/#create-or-update-user was that specifiying user_id or email should allow me to update the user, and that id is not required?

> Note that the following lookup order applies when updating users - id then user_id then email, and results in the following logic -

> id is matched - the user_id and email will be updated if they are sent.
user_id match - the email will be updated, the id is not updated.
email match - the user_id will be updated if sent, the id is not updated if sent.

**Comment by josler** [comment]
You're absolutely right - we do not require the `id` field.

You can use `createUser` instead for now, it will result in the same request to Intercom.

**Comment by rb-cohen** [comment]
Thanks josier. I'll try to raise a pull request later today.
