### ISSUE TITLE
Problem with  save user data

### ISSUE THREAD

**Issue by natalyaholyk** [intercom/intercom-php#78]
Hello, 
I am using intercom-php and try to save user info, 
1)  can't save information like: avatar, or social_profiles
$newUser = $intercom->createUser(array(
                            "email" => 'test@gmail.com',
                            "name" => 'Hello World',
                            "last_request_at" => time(),
                            "created_at" => time(),
                            "avatar" => array(
                                "type" => "avatar",
                                "image_url" => 'http://url.to.image'
                            ),
                            "location_data" => array(
                                "type" => "location_data",
                                "latitude" => $location[1],
                                "longitude" => $location[0]
                            ),
                            "social_profiles" => array(
                                "type" => "social_profile",
                                "name" =>"facebook",
                                "id" => '1234',
                                "username" => 'Facebook User Name',
                                "url" => 'http://facebook.url'
                            )
                        ));
In intercom user with email 'test@gmail.com' was created , but avatar and social_profiles data are empty. 
What I missed?
2) Can't create message from user..
$text = $intercom->createMessage(array(
                            "message_type" => "inapp",
                            "subject" => $subject,
                            "body" => $text,
                            "template" => "plain",
                            "from" => array(
                                "type" => "user",
                                "id" => '123a'
                            ),
                            "to" => array(
                                "type" => "user",
                                "id" => '123b'
                            )
                        ));
Users Ids : '123a' & '123b' - exist in intercom. 
Any ideas??
P.S. There are no errors in both cases.

**Comment by josler** [comment]
Hi @natalyaholyk,

It's not possible to update Avatar or Social Profiles through Intercom directly; we pull those details from elsewhere (usually using the email address).

The fields that can be updated are detailed in the source code of this client here: https://github.com/intercom/intercom-php/blob/master/src/Intercom/Service/config/intercom_public_user.json#L49 or in the api docs here: http://doc.intercom.io/api/#create-or-update-user.

Thanks
