### ISSUE TITLE
createEvent error

### ISSUE THREAD

**Issue by bormansquirrel** [intercom/intercom-php#79]
Hi, first time I'm using intercom-php client.

I get this error all the time: 

failed: Client error response 
[status code] 404
[reason phrase] Not Found
[url] https://api.intercom.io/events

This code is working
``` php
        try {
            $this->intercom->updateUser(
                [
                    'email' => $event->getUserEmail(),
                    'last_request_at' => time(),
                    'custom_attributes' => $event->getUserProperty()
                ]
            );

        } catch (ServerErrorResponseException $e) {

        } catch (ClientErrorResponseException $e) {

        }
``` 

This code is not:
``` php
        try {
            $this->intercom->createEvent(
                array(
                    "event_name" => $event->getEventName(),
                    "email" => $event->getUserEmail(),
                    "created_at" => time(),
                )
            );
        } catch (ServerErrorResponseException $e) {

        } catch (ClientErrorResponseException $e) {

        }
``` 
I have tried with the examples of the documentation as well but I still get the same error ...

Any idea what would be is happening?

Thanks!

**Comment by josler** [comment]
Hi @bormansquirrel,

Users have to exist in Intercom before an event can be created against them. Is that the case here? If it's still a problem you can contact me through Intercom with your App ID and I'll take a look further.

Thanks!

**Comment by bormansquirrel** [comment]
Hi @josler,

It seems that when a user its created by updateUser (that is, when a user did not exist) it has not being the same effect in terms of 'user creation' than when you create a user explicitly with createUser method. I say that because if a user its created with updateUser the createEvent will not work against that user. 

Am I right? Would be interesting the get this working if I'm true isn't it?

Just for the record after creating a user with createUser its working.

Thanks!

**Comment by josler** [comment]
`updateUser` and `createUser` should be equivalent - it's a create or update operation and both should create a user.

**Comment by bormansquirrel** [comment]
Yes you're right! Forget all about that. It was a malformed data ... Sorry about that, this issue never should exists.

Really appreciate the support! Thanks!
