### ISSUE TITLE
getUser returns an iterator?

### ISSUE THREAD

**Issue by dandart** [intercom/intercom-php#84]
Hi,

I was trying to do this:

$intercom = \Intercom\IntercomBasicAuthClient::factory([
                'app_id' => 'xyxyxyxy',
                'api_key' => 'yxyxyxyxyx'
            ]);

$iUser = $intercom->getUser(
            [
                'email' => $someEmail
            ]
        );

however I just get a list - and the first user in the list doesn't even have that email address.

Is there a problem with the API or the way I'm using it?
Cheers

**Comment by josler** [comment]
Hi @dandart - that seems correct, and works here for me:

`$found_user = $intercom->getUser(['email' => 'myemail@intercom.io']);`

Could you send me the full request/response you're getting? If not here then through Intercom.

Thanks!

**Comment by dandart** [comment]
Thanks,

How do I get hold of the requests/responses and also you via Intercom?

Cheers

**Comment by josler** [comment]
Any logs you have, or time windows, along with the code and email being sent would be great.

You can use the Intercom messenger when you're logged into Intercom and just mention me.

**Comment by bobjflong** [comment]
@dandart did you reach a resolution here?

**Comment by dandart** [comment]
I don't believe so, last I tried I was still getting this.
