### ISSUE TITLE
Support for Bulk user creation

### ISSUE THREAD

**Issue by ebuildy** [intercom/intercom-php#86]
Hello,

Is it possible to use bulk user creation ? (from https://doc.intercom.io/api/#bulk-user-creation).

Or is it something planed ?

Thanks you,

Thomas Decaux

**Comment by dimsav** [comment]
:+1: also for updating users.

@ebuildy [here](https://github.com/intercom/intercom-php/blob/master/src/Intercom/Service/config/intercom_public_user.json) is the list of the available user requests.

**Comment by bobjflong** [comment]
Hey, I've added support for the new Bulk APIs in v1.3.0: https://github.com/intercom/intercom-php#bulk-api
