### ISSUE TITLE
[Feature] IDE autocompletion

### ISSUE THREAD

**Issue by dimsav** [intercom/intercom-php#89]
It would be a nice feature to allow IDE autocompletion by adding a dockblock at the top of `IntercomBasicAuthClient` or `IntercomAbstractClient`.

Example: 

```php
/**
  * @method Returned_Class methodName(TypeHint $typehint, TypeHint2 $typehint2) And a comment to describe what the method does
  */
class IntercomBasicAuthClient {}
```

This will also allow users to know what requests are supported and what not. See #86

**Comment by sylfabre** [comment]
+1

**Comment by francescomalatesta** [comment]
+1
