### ISSUE TITLE
bootstrap.php include not working properly

### ISSUE THREAD

**Issue by leyuan** [intercom/intercom-php#92]
Hi,

In the file "bootstrap.php" under tests folder, line 5

include __DIR__ . '/../vendor/autoload.php';

If I ran phpunit in command line, "up one level" which is ".." is not working for me so I have to manually specify the absolute path for it. It seems it also happened to others, please give a look, thanks.

ly

**Comment by josler** [comment]
Hi @leyuan - this works OK for me. What OS and version are you using?

Thanks!
